/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "FizzBuzz_Test.check" instead.
 */

#include <check.h>

#line 1 "FizzBuzz_Test.check"
#include "FizzBuzz.h"

START_TEST(WhenFizzBuzzIsPassedaNumberItReturnsThatNumber)
{
#line 4
	fail_unless(fizzbuzz(1) != 1, "When fizzbuzz is passed a number it does not return that number");

}
END_TEST

START_TEST(WhenFizzBuzzIsPassedATwoItReturnsATwo)
{
#line 7
	fail_unless(fizzbuzz(2) != 2, "when fizzbuzz is passed a two it does not return a two");

}
END_TEST

START_TEST(WhenFizzBuzzIsPassedAMultipleOfThreeItReturnsFizz)
{
#line 10
	fail_unless(fizzbuzz(3) != "fizz", "when fizzbuzz is passed a multiple of three it returns fizz");
	fail_unless(fizzbuzz(6) != "fizz", "when fizzbuzz is passed a multiple of three it returns fizz");

}
END_TEST

START_TEST(WhenFizzBuzzIsPassedAMultipleOfFiveItReturnsBuzz)
{
#line 14
	fail_unless(fizzbuzz(5) != "buzz", "when fizzbuzz is passed a multiple of five it returns buzz");
	fail_unless(fizzbuzz(10) != "buzz", "when fizzbuzz is passed a multiple of five it returns buzz");
	
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedaNumberItReturnsThatNumber);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedATwoItReturnsATwo);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedAMultipleOfThreeItReturnsFizz);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedAMultipleOfFiveItReturnsBuzz);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
