/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "FizzBuzz_Test.check" instead.
 */

#include <check.h>

#line 1 "FizzBuzz_Test.check"
#include "FizzBuzz.h"

int match;

START_TEST(WhenFizzBuzzIsPassedaNumberItReturnsThatNumber)
{
#line 6
	match = strcmp(fizzbuzz(1),"1");
	fail_unless(match == 0, "When fizzbuzz is passed a number it does not return that number");

}
END_TEST

START_TEST(WhenFizzBuzzIsPassedATwoItReturnsATwo)
{
#line 10
	match = strcmp(fizzbuzz(2),"2");	
	fail_unless(match == 0, "when fizzbuzz is passed a two it does not return a two");

}
END_TEST

START_TEST(WhenFizzBuzzIsPassedAMultipleOfThreeItReturnsFizz)
{
#line 14
	match = strcmp(fizzbuzz(3),"fizz");	
	fail_unless(match == 0, "when fizzbuzz is passed a multiple of three it returns fizz");
	match = strcmp(fizzbuzz(6),"fizz");
	fail_unless(match == 0, "when fizzbuzz is passed a multiple of three it returns fizz");

}
END_TEST

START_TEST(WhenFizzBuzzIsPassedAMultipleOfFiveItReturnsBuzz)
{
#line 20
	match = strcmp(fizzbuzz(5),"buzz");	
	fail_unless(match == 0, "when fizzbuzz is passed a multiple of five it returns buzz");
	match = strcmp(fizzbuzz(10),"buzz");	
	fail_unless(match == 0, "when fizzbuzz is passed a multiple of five it returns buzz");

}
END_TEST

START_TEST(WhenFizzBuzzIsPassedAMultipleOfThreeAndFiveItReturnsFizzBuzz)
{
#line 26
	match = strcmp(fizzbuzz(15),"fizzbuzz");		
	fail_unless(match == 0, "when fizzbuzz is passed a multiple of three and five it returns fizzbuzz");
	
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedaNumberItReturnsThatNumber);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedATwoItReturnsATwo);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedAMultipleOfThreeItReturnsFizz);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedAMultipleOfFiveItReturnsBuzz);
    tcase_add_test(tc1_1, WhenFizzBuzzIsPassedAMultipleOfThreeAndFiveItReturnsFizzBuzz);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
